### ISSUE TITLE
Insanely high cpu usage.

### ISSUE THREAD

**Issue by TouhouJevil** [Electr0Gunner/PvZ-Quality-of-the-Lawn-Decompile#12]
I have no idea why but the more recent versions of this decomp (ex: 1.4.3) uses a giant amount of my cpu compared to the older versions.

For reference the standard decomp from MA, uses around 50-60% of my cpu (i have 2 cores, so that is actually more like 25-30%) this is just the normal game, no visual studio open.

Meanwhile if i use the most recent version of this decomp (1.4.3) with again the normal game, no visual studio open, i end up using 227%-240% of my cpu so that is legit 4x more than the standard MA decomp.

And yes i did tried to turn off discord presence in the settings, turn on and off 3d acceleration and etc, this decomp really just use way more of my cpu.

For reference my processor is Intel(R) Celeron(R) N4020 CPU @ 1.10GHz 1.10 GHz, it has 4 gb ram, 64 bits and uses windows 10 pro, i understand this is not the strongest pc out there but it shouldn't be dying to just run pvz1 and like i said it runs the MA decomp/standard pvz1 completely fine.

**Comment by TouhouJevil** [comment]
Forgot to say on the previous post, if you want to contact me directly for help with testing and etc, my discord tag is raphielshiraha64.

**Comment by Electr0Gunner** [comment]
![image](https://github.com/Electr0Gunner/PvZ-Quality-of-the-Lawn-Decompile/assets/114804446/2492e8a9-29bb-48bc-9f0d-5c911fce2107)
interesting issue
try to remove the dlls from the following image
or test an older version ex: v1.1.0 or v1.2.0
as its closer to the og decomp for test

**Comment by TouhouJevil** [comment]
> ![image](https://private-user-images.githubusercontent.com/114804446/342093933-2492e8a9-29bb-48bc-9f0d-5c911fce2107.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNzI4NDksIm5iZiI6MTcxOTE3MjU0OSwicGF0aCI6Ii8xMTQ4MDQ0NDYvMzQyMDkzOTMzLTI0OTJlOGE5LTI5YmItNDhiYy05ZjBkLTVjOTExZmNlMjEwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxOTU1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2U3YWQ1YmRiZGYyMGQ0YzU4MjE3NWQyNDcyNmNkZDQ2ZjFiMWFhZTEzNmJkZTQwNmFhMzNmYTJkMTFjMmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JGn1c71cDlOkoE2cX0WVOb3RAe4VLB-_ljkdMlJOSBc) interesting issue try to remove the dlls from the following image or test an older version ex: v1.1.0 or v1.2.0 as its closer to the og decomp for test

It worked! performance sky rocketed, thank you.
