### ISSUE TITLE
Keybinds Toggle not working.

### ISSUE THREAD

**Issue by TouhouJevil** [Electr0Gunner/PvZ-Quality-of-the-Lawn-Decompile#13]
When i toggle on the keybinds option on the advanced options menu, and close the menu it automatically undo the toggle, then if i open the advanced options again to check i will notice the checkmark on the keybinds is no longer there basically making that menu option unusable.

**Comment by BULL3TB0T** [comment]
are you pressing ESCAPE when you quit from the advanced options menu? if so then it won't save it.

**Comment by Electr0Gunner** [comment]
Its probably fixed in the latest patch
